os: windows
language: bash

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed base base-devel sh mpfr libintl libreadline gettext-devel mpfr-devel libreadline-devel
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/bin:$PATH
        export MAKE=make  # so that Autotools can find it
        ;;
    esac

script:
  - echo $PATH
  - mkdir -p bld-m1 && cd bld-m1 && sh ../configure --without-libiconv-prefix --without-libintl-prefix --without-libsigsegv && make && make check
  - autoreconf -vfi && mkdir -p bld-m2 && cd bld-m2 && sh ../configure --without-libiconv-prefix --without-libintl-prefix --without-libsigsegv && make && make check && make distcheck

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
